mutation {
  addActivity(input: {title: "New Activity", description: "Lets go", projectId: "P1", creatorId: "U1"}) {
    newActivity {
      id
    }
  }
}

query {projects {id,
  owner {id, login, name, email},
  activities { id, title, state, creator { login }}
}}

query {project(id:"P1") {activities {id, title, assignee { id, name }}}}

mutation {assignActivity(input:{activityId: "A2" assigneeId: "U3"}) {activity {id, title}}}


query {
  projects {activities {id, state, nextAction }}
}

mutation
	{promoteActivity(input: {activityId:"A3"})
    {promoteSuccessful activity { id, state, nextAction}}
  }


	mutation
	{createUser(input:{login: "xxx", email: "a@b", name: "Xxx"}) {newUser {id, name, login}}}
mutation {
  createProject(input:
    {key:"PRO1", title:"A Project", description: "What else?", ownerId:"U100"})
  {newProject {id, key, owner { id, name, login, projects { id, key } } } } }



mutation {updateUser
 (input: {id: "U1" name: "Klaus-Dieter" email: "kd@mail.net"})
  {updatedUser {id, login, name, email}}}

mutation {updateProject
 (input: {id: "P1" title: "My Project" description: "My very new project"})
  {updatedProject {id, key, title, description}}}
